export const GET_GROUPDATA_LOADING = 'GET_GROUPDATA_LOADING';
export const GET_GROUPDATA_SUCCESS = 'GET_GROUPDATA_SUCCESS';
export const GET_GROUPDATA_FAIL = 'GET_GROUPDATA_FAIL';

export const GET_GROUP_ALBUMS_SUCCESS = 'GET_GROUP_ALBUMS_SUCCESS';
export const GET_GROUP_ALBUMS_FAIL = 'GET_GROUP_ALBUMS_FAIL';
export const GET_GROUP_ALBUMS_LOADING = 'GET_GROUP_ALBUMS_LOADING';

export const ADD_NEW_ALBUM_LOADING = 'ADD_NEW_ALBUM_LOADING';
export const ADD_NEW_ALBUM_SUCCESS = 'ADD_NEW_ALBUM_SUCCESS';
export const ADD_NEW_ALBUM_FAIL = 'ADD_NEW_ALBUM_FAIL';

export const CLEAR_GROUP_DATA = 'CLEAR_GROUP_DATA';
export const SEARCH_ALBUMS = 'SEARCH_ALBUMS';
