export const GET_ALL_USER_GROUPS_LOADING = 'GET_ALL_USER_GROUPS_LOADING';
export const GET_ALL_USER_GROUPS_SUCCES = 'GET_ALL_USER_GROUPS_SUCCES';
export const GET_ALL_USER_GROUPS_FAIL = 'GET_ALL_USER_GROUPS_FAIL';

export const ADD_NEW_GROUP_LOADING = 'ADD_NEW_GROUP_LOADING';
export const ADD_NEW_GROUP_SUCCESS = 'ADD_NEW_GROUP_SUCCESS';
export const ADD_NEW_GROUP_FAIL = 'ADD_NEW_GROUP_FAIL';

export const SEARCH_GROUPS = 'SEARCH_GROUPS';
