export const GET_ALL_USER_GROUPS_LOADING = 'GET_ALL_USER_GROUPS_LOADING';
export const GET_ALL_USER_GROUPS_SUCCES = 'GET_ALL_USER_GROUPS_SUCCES';
export const GET_ALL_USER_GROUPS_FAIL = 'GET_ALL_USER_GROUPSFAIL';
