export const GET_ALBUM_DATA_LOADING = 'GET_ALBUM_DATA_LOADING';
export const GET_ALBUM_DATA_SUCCESS = 'GET_ALBUM_DATA_SUCCESS';
export const GET_ALBUM_DATA_FAIL = 'GET_ALBUM_DATA_FAIL';

export const GET_ALBUMDATA_LOADING = 'GET_ALBUMDATA_LOADING';
export const GET_ALBUMDATA_SUCCESS = 'GET_ALBUMDATA_SUCCESS';
export const GET_ALBUMDATA_FAIL = 'GET_ALBUMDATA_FAIL';

export const GET_ALBUM_POSTS_LOADING = 'GET_ALBUM_POSTS_LOADING';
export const GET_ALBUM_POSTS_SUCCESS = 'GET_ALBUM_POSTS_SUCCESS';
export const GET_ALBUM_POSTS_FAIL = 'GET_ALBUM_POSTS_FAIL';

export const CLEAR_ALBUM_DATA = 'CLEAR_ALBUM_DATA';
export const SEARCH_POSTS = 'SEARCH_POSTS';

export const ADD_NEW_POST_LOADING = 'ADD_NEW_POST_LOADING';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL';
